<html>
<head>
<title>TestNG:  ParallelRegression</title>
<link href="../testng.css" rel="stylesheet" type="text/css" />
<link href="../my-testng.css" rel="stylesheet" type="text/css" />

<style type="text/css">
.log { display: none;} 
.stack-trace { display: none;} 
</style>
<script type="text/javascript">
<!--
function flip(e) {
  current = e.style.display;
  if (current == 'block') {
    e.style.display = 'none';
    return 0;
  }
  else {
    e.style.display = 'block';
    return 1;
  }
}

function toggleBox(szDivId, elem, msg1, msg2)
{
  var res = -1;  if (document.getElementById) {
    res = flip(document.getElementById(szDivId));
  }
  else if (document.all) {
    // this is the way old msie versions work
    res = flip(document.all[szDivId]);
  }
  if(elem) {
    if(res == 0) elem.innerHTML = msg1; else elem.innerHTML = msg2;
  }

}

function toggleAllBoxes() {
  if (document.getElementsByTagName) {
    d = document.getElementsByTagName('div');
    for (i = 0; i < d.length; i++) {
      if (d[i].className == 'log') {
        flip(d[i]);
      }
    }
  }
}

// -->
</script>

</head>
<body>
<h2 align='center'>ParallelRegression</h2><table border='1' align="center">
<tr>
<td>Tests passed/Failed/Skipped:</td><td>8/0/2</td>
</tr><tr>
<td>Started on:</td><td>Sun May 18 16:32:09 WIB 2025</td>
</tr>
<tr><td>Total time:</td><td>3 seconds (3554 ms)</td>
</tr><tr>
<td>Included groups:</td><td></td>
</tr><tr>
<td>Excluded groups:</td><td></td>
</tr>
</table><p/>
<small><i>(Hover the method name to see the test class name)</i></small><p/>
<table width='100%' border='1' class='invocation-passed'>
<tr><td colspan='4' align='center'><b>PASSED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td><b>Attribute(s)</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='testng.SimpleTest.testMethod()'><b>testMethod</b><br>Test class: testng.SimpleTest</td>
<td></td>
<td>1</td>
<td>testng.SimpleTest@bb12f41</td></tr>
<tr>
<td title='testng.AssertTest.testMethod()'><b>testMethod</b><br>Test class: testng.AssertTest</td>
<td></td>
<td>0</td>
<td>testng.AssertTest@3739f3c9</td></tr>
<tr>
<td title='testng.DataProviderTest.testMethod()'><b>testMethod</b><br>Test class: testng.DataProviderTest<br>Parameters: 4567, inactive</td>
<td></td>
<td>0</td>
<td>testng.DataProviderTest@7ab2ba47</td></tr>
<tr>
<td title='testng.DataProviderTest.testMethod()'><b>testMethod</b><br>Test class: testng.DataProviderTest<br>Parameters: 1255, active</td>
<td></td>
<td>0</td>
<td>testng.DataProviderTest@7ab2ba47</td></tr>
<tr>
<td title='testng.RetryTest.flackyTest()'><b>flackyTest</b><br>Test class: testng.RetryTest</td>
<td></td>
<td>0</td>
<td>testng.RetryTest@40fe8fd5</td></tr>
<tr>
<td title='testng.SimpleTest.testMethod2()'><b>testMethod2</b><br>Test class: testng.SimpleTest</td>
<td></td>
<td>2</td>
<td>testng.SimpleTest@bb12f41</td></tr>
<tr>
<td title='testng.SimpleTest.testMethod3()'><b>testMethod3</b><br>Test class: testng.SimpleTest</td>
<td></td>
<td>0</td>
<td>testng.SimpleTest@bb12f41</td></tr>
<tr>
<td title='testng.DataProviderTest.testMethod()'><b>testMethod</b><br>Test class: testng.DataProviderTest<br>Parameters: 1234, active</td>
<td></td>
<td>0</td>
<td>testng.DataProviderTest@7ab2ba47</td></tr>
</table><p>
<table width='100%' border='1' class='invocation-skipped'>
<tr><td colspan='4' align='center'><b>SKIPPED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td><b>Attribute(s)</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='testng.RetryTest.flackyTest()'><b>flackyTest</b><br>Test class: testng.RetryTest</td>
<td><div><pre>java.lang.AssertionError: expected [true] but found [false]
	at testng.RetryTest.flackyTest(RetryTest.java:15)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1095)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:619)
	at java.base/java.lang.Thread.run(Thread.java:1447)
... Removed 15 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace783484850", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace783484850'><pre>java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.failNotEquals(Assert.java:1590)
	at org.testng.Assert.assertTrue(Assert.java:57)
	at org.testng.Assert.assertTrue(Assert.java:67)
	at testng.RetryTest.flackyTest(RetryTest.java:15)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
	at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
	at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1095)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:619)
	at java.base/java.lang.Thread.run(Thread.java:1447)
</pre></div></td>
<td>0</td>
<td>testng.RetryTest@40fe8fd5</td></tr>
<tr>
<td title='testng.RetryTest.flackyTest()'><b>flackyTest</b><br>Test class: testng.RetryTest</td>
<td><div><pre>java.lang.AssertionError: expected [true] but found [false]
	at testng.RetryTest.flackyTest(RetryTest.java:15)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1095)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:619)
	at java.base/java.lang.Thread.run(Thread.java:1447)
... Removed 15 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1141517740", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1141517740'><pre>java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.failNotEquals(Assert.java:1590)
	at org.testng.Assert.assertTrue(Assert.java:57)
	at org.testng.Assert.assertTrue(Assert.java:67)
	at testng.RetryTest.flackyTest(RetryTest.java:15)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
	at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1095)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:619)
	at java.base/java.lang.Thread.run(Thread.java:1447)
</pre></div></td>
<td>0</td>
<td>testng.RetryTest@40fe8fd5</td></tr>
</table><p>
</body>
</html>